# Generated by Django 3.0.7 on 2020-06-26 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('short_id', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TaskInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coding', models.BooleanField(default=False)),
                ('testing', models.BooleanField(default=False)),
                ('req_analysis', models.BooleanField(default=False)),
                ('user_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.UserInfo')),
            ],
        ),
    ]
